pins:
  - pin: 1C
    # H144_LS_8
    id: F14
    function: Injector 8
    class: outputs
    type: inj
    ts_name: 1C - Injector 8
    color: blue

  - pin: 2C
    function: Injector 7
    class: outputs
    type: inj
    ts_name: 2C - Injector 7
    color: blue
    
  - pin: 3C
    function: Injector 6
    class: outputs
    type: inj
    ts_name: 3C - Injector 6
    color: blue
    
  - pin: 4C
    function: Injector 5
    class: outputs
    type: inj
    ts_name: 4C - Injector 5
    color: blue
    
  - pin: 5C
    function: Switch4 (5v pull-up, with hysteresis)
    # H144_IN_MAP3_DIGITAL
    id: A2
    class: event_inputs
    ts_name: 5C - Switch4

  - pin: 6C
    # H144_IN_AUX2
    id: EFI_ADC_14
    class: analog_inputs
    function: PPS1 Sensor Input
    ts_name: 6C - PPS1
    color: orange
    
  - pin: 7C
    function: ETB positive
    type: etb
    ts_name: 7C - ETB+
    color: purple
    
  - pin: 8C
    function: ETB negative
    type: etb
    ts_name: 7C - ETB-
    color: purple

  - pin: 9C
    function: Power GND
    type: gnd

  - pin: 10C
    class: outputs
    function: Smart Ignition 8 Output
    type: ign
    ts_name: 10C - Ignition 8
    color: yellow
    
  - pin: 11C
    class: outputs
    function: Smart Ignition 7 Output
    type: ign
    ts_name: 10C - Ignition 7
    color: yellow

  - pin: 12C
    class: outputs
    function: Smart Ignition 6 Output
    type: ign
    ts_name: 10C - Ignition 6
    color: yellow

  - pin: 13C
    class: outputs
    function: Smart Ignition 5 Output
    type: ign
    ts_name: 10C - Ignition 5
    color: yellow

  - pin: 14C
    function: Power Ground
    color: black
    type: gnd

  - pin: 15C
    # H144_IN_TPS AIN17 PA4
    id: EFI_ADC_4
    class: analog_inputs
    function: TPS Sensor Input
    ts_name: 23C - TPS
    color: orange

  - pin: 16C
    # H144_IN_AUX1
    id: EFI_ADC_8
    class: analog_inputs
    function: TPS2 Sensor Input
    ts_name: 24C - TPS2
    color: orange

  - pin: 17C
    function: Power Ground
    color: black
    type: gnd

  - pin: 18C
    # H144_IGN_8
    id: E6
    class: outputs
    function: Smart Ignition 12 Output
    type: ign
    ts_name: 18C - Ignition 12
    color: yellow

  - pin: 19C
    # H144_IGN_7
    id: B9
    class: outputs
    function: Smart Ignition 11 Output
    type: ign
    ts_name: 19C - Ignition 11
    color: yellow

  - pin: 20C
    # H144_IGN_6
    id: B8
    class: outputs
    function: Smart Ignition 10 Output
    type: ign
    ts_name: 20C - Ignition 10
    color: yellow

  - pin: 21C
    # H144_IGN_5
    id: E2
    class: outputs
    function: Smart Ignition 9 Output
    type: ign
    ts_name: 21C - Ignition 9
    color: yellow
    
  - pin: 22C
    # H144_IN_TPS AIN17 PA4
    id: EFI_ADC_4
    class: analog_inputs
    function: Analog2
    ts_name: 22C - Analog2
    color: orange
    
  - pin: 23C
    # H144_IN_TPS AIN17 PA4
    id: EFI_ADC_4
    class: analog_inputs
    function: Analog3
    ts_name: 23C - Analog3
    color: orange
  
  - pin: 24C
    # H144_IN_TPS AIN17 PA4
    id: EFI_ADC_4
    class: analog_inputs
    function: Analog4
    ts_name: 24C - Analog4
    color: orange

  - pin: 25C
    function: Analog Ground
    color: black
    type: gnd

  - pin: 26C
    function: Injector 12
    class: outputs
    type: inj
    ts_name: 26C - Injector 12
    color: blue

  - pin: 27C
    # H144_LS_7
    id: F13
    function: Injector 11
    class: outputs
    type: inj
    ts_name: 27C - Injector 11
    color: blue

  - pin: 28C
    # H144_LS_6
    id: F12
    function: Injector 10
    class: outputs
    type: inj
    ts_name: 28C - Injector 10
    color: blue

  - pin: 29C
    # H144_LS_5
    id: D9
    function: Injector 9
    class: outputs
    type: inj
    ts_name: 29C - Injector 9
    color: blue

  - pin: 30C
    function: 12v raw in? out?
    type: 12v

  - pin: 31C
    # H144_IN_IAT + 16 = 14 + 16
    id: EFI_ADC_30
    class: analog_inputs
    function: Temperature 3
    ts_name: 6C - AT3
    color: orange

  - pin: 32C
    # EFI_ADC_12 + 16 = 12 + 16
    id: EFI_ADC_28
    class: analog_inputs
    function: Temperature 4
    ts_name: 7C - AT4
    color: orange

  - pin: 33C
    ts_name: ___ KNOCK2
    function: knock2 sensor signal

  - pin: 34C
    ts_name: ___ KNOCK1
    function: knock1 sensor signal

info:
  title: AlphaX 8chan
  name: AlphaX 8chan
  image:
    file: 34pins-4k.jpg
  pins:
    - pin: 1C
      x: 75
      y: 90
    - pin: 2C
      x: 95
      y: 90
    - pin: 3C
      x: 120
      y: 90
    - pin: 4C
      x: 145
      y: 90
    - pin: 5C
      x: 165
      y: 90
    - pin: 6C
      x: 190
      y: 90
    - pin: 7C
      x: 215
      y: 90
    - pin: 8C
      x: 240
      y: 90
    - pin: 9C
      x: 265
      y: 90
    - pin: 10C
      x: 85
      y: 120
    - pin: 11C
      x: 105
      y: 120
    - pin: 12C
      x: 130
      y: 120
    - pin: 13C
      x: 155
      y: 120
    - pin: 14C
      x: 180
      y: 120
    - pin: 15C
      x: 205
      y: 120
    - pin: 16C
      x: 225
      y: 120
    - pin: 17C
      x: 245
      y: 120
    - pin: 18C
      x: 85
      y: 150
    - pin: 19C
      x: 110
      y: 150
    - pin: 20C
      x: 130
      y: 150
    - pin: 21C
      x: 155
      y: 150
    - pin: 22C
      x: 180
      y: 150
    - pin: 23C
      x: 205
      y: 150
    - pin: 24C
      x: 225
      y: 150
    - pin: 25C
      x: 245
      y: 150
    - pin: 26C
      x: 74
      y: 180
    - pin: 27C
      x: 98
      y: 180
    - pin: 28C
      x: 122
      y: 180
    - pin: 29C
      x: 146
      y: 180
    - pin: 30C
      x: 170
      y: 180
    - pin: 31C
      x: 195
      y: 180
    - pin: 32C
      x: 220
      y: 180
    - pin: 33C
      x: 245
      y: 180
    - pin: 34C
      x: 265
      y: 180
